# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: qctet

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: pwd
      run: |
        pwd
        date
        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        date
