# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: qctet

on:
  push:
    branches: [ main ]

jobs:
  update:
    name: Update QC infomation
    runs-on: ubuntu-latest
    
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      
      - name: Update QC infomation
        run: |
          python update.py 1>update.log 2>err.log
          echo '\n'
          cat update.log
          echo '\n'
          cat err.log
          
          echo 'NEWQC<<EOF' >> $GITHUB_ENV
          git diff --stat|wc -l >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
          echo 'MSG<<EOF' >> $GITHUB_ENV
          cat update.log >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Set SSH-Key
        if: env.NEWQC > 0
        env:
          SSH_KEY: ${{secrets.gitee_ssh_key}}
          SSH_KEY_PUB: ${{secrets.gitee_ssh_key_pub}}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
          echo ${SSH_KEY} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo ${SSH_KEY_PUB} > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
      
      - name: Git config
        if: env.NEWQC > 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          #git config --local commit.template ./update.log
      
      - name: Commit Files
        if: env.NEWQC > 0
        run: |
          git add list zhikong.txt
          git commit -m ${{ env.MSG }}
